CREATE TABLE "email_verification_challenges" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "email_verification_challenges_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"email" varchar(254) NOT NULL,
	"purpose" varchar(40) NOT NULL,
	"user_id" integer,
	"guest_session_hash" varchar(64),
	"pin_hash" varchar(64) NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"failed_attempts" integer DEFAULT 0 NOT NULL,
	"last_sent_at" timestamp with time zone NOT NULL,
	"verified_at" timestamp with time zone,
	"consumed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "email_verification_purpose_check" CHECK ("email_verification_challenges"."purpose" in ('CLIENT_REGISTRATION', 'CLIENT_EMAIL_CHANGE', 'GUEST_CHECKOUT')),
	CONSTRAINT "email_verification_owner_check" CHECK ((
        "email_verification_challenges"."purpose" in ('CLIENT_REGISTRATION', 'CLIENT_EMAIL_CHANGE')
        and "email_verification_challenges"."user_id" is not null
        and "email_verification_challenges"."guest_session_hash" is null
      ) or (
        "email_verification_challenges"."purpose" = 'GUEST_CHECKOUT'
        and "email_verification_challenges"."user_id" is null
        and "email_verification_challenges"."guest_session_hash" is not null
        and length("email_verification_challenges"."guest_session_hash") = 64
      )),
	CONSTRAINT "email_verification_pin_hash_check" CHECK (length("email_verification_challenges"."pin_hash") = 64),
	CONSTRAINT "email_verification_attempts_check" CHECK ("email_verification_challenges"."failed_attempts" >= 0 and "email_verification_challenges"."failed_attempts" <= 5),
	CONSTRAINT "email_verification_expiry_check" CHECK ("email_verification_challenges"."expires_at" > "email_verification_challenges"."created_at")
);
--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "email_verified_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "email_verification_challenges" ADD CONSTRAINT "email_verification_challenges_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "email_verification_email_sent_idx" ON "email_verification_challenges" USING btree ("email","last_sent_at");--> statement-breakpoint
CREATE INDEX "email_verification_user_sent_idx" ON "email_verification_challenges" USING btree ("user_id","last_sent_at");--> statement-breakpoint
CREATE INDEX "email_verification_guest_sent_idx" ON "email_verification_challenges" USING btree ("guest_session_hash","last_sent_at");--> statement-breakpoint
CREATE UNIQUE INDEX "email_verification_active_user_unique" ON "email_verification_challenges" USING btree ("user_id","purpose") WHERE "email_verification_challenges"."user_id" is not null and "email_verification_challenges"."consumed_at" is null;--> statement-breakpoint
CREATE UNIQUE INDEX "email_verification_active_guest_unique" ON "email_verification_challenges" USING btree ("guest_session_hash","purpose") WHERE "email_verification_challenges"."guest_session_hash" is not null and "email_verification_challenges"."consumed_at" is null;
