ALTER TABLE "customer_notice" RENAME COLUMN "active" TO "is_active";--> statement-breakpoint
ALTER TABLE "customer_notice" DROP CONSTRAINT "customer_notice_singleton_check";--> statement-breakpoint
ALTER TABLE "customer_notice" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "customer_notice" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "customer_notice_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "customer_notice" ALTER COLUMN "title" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "customer_notice" ALTER COLUMN "message" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "customer_notice" ADD COLUMN "sort_order" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "customer_notice" ADD COLUMN "display_seconds" integer DEFAULT 7 NOT NULL;--> statement-breakpoint
ALTER TABLE "customer_notice" ADD COLUMN "starts_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "customer_notice" ADD COLUMN "ends_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "customer_notice" ADD COLUMN "created_by_user_id" integer;--> statement-breakpoint
UPDATE "customer_notice"
SET "created_by_user_id" = "updated_by_user_id"
WHERE "created_by_user_id" IS NULL;--> statement-breakpoint
SELECT setval(
	pg_get_serial_sequence('customer_notice', 'id'),
	COALESCE(MAX("id"), 1),
	MAX("id") IS NOT NULL
)
FROM "customer_notice";--> statement-breakpoint
ALTER TABLE "customer_notice" ADD CONSTRAINT "customer_notice_created_by_user_id_users_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "customer_notice" ADD CONSTRAINT "customer_notice_sort_order_check" CHECK ("customer_notice"."sort_order" >= 0);--> statement-breakpoint
ALTER TABLE "customer_notice" ADD CONSTRAINT "customer_notice_display_seconds_check" CHECK ("customer_notice"."display_seconds" between 3 and 30);--> statement-breakpoint
ALTER TABLE "customer_notice" ADD CONSTRAINT "customer_notice_validity_check" CHECK ("customer_notice"."starts_at" is null or "customer_notice"."ends_at" is null or "customer_notice"."ends_at" > "customer_notice"."starts_at");
