CREATE TABLE "promotion_categories" (
	"promotion_id" integer NOT NULL,
	"category_id" integer NOT NULL,
	CONSTRAINT "promotion_categories_promotion_id_category_id_pk" PRIMARY KEY("promotion_id","category_id")
);
--> statement-breakpoint
CREATE TABLE "promotion_products" (
	"promotion_id" integer NOT NULL,
	"product_id" integer NOT NULL,
	CONSTRAINT "promotion_products_promotion_id_product_id_pk" PRIMARY KEY("promotion_id","product_id")
);
--> statement-breakpoint
CREATE TABLE "promotions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "promotions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(160) NOT NULL,
	"type" varchar(40) NOT NULL,
	"is_active" boolean DEFAULT false NOT NULL,
	"percentage" integer,
	"starts_at" timestamp with time zone DEFAULT now() NOT NULL,
	"ends_at" timestamp with time zone,
	"created_by_user_id" integer,
	"updated_by_user_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "promotions_type_check" CHECK ("promotions"."type" in ('PERCENTAGE_DISCOUNT', 'BUY_2_PAY_1')),
	CONSTRAINT "promotions_percentage_check" CHECK ((
        ("promotions"."type" = 'PERCENTAGE_DISCOUNT' and "promotions"."percentage" between 1 and 99)
        or ("promotions"."type" = 'BUY_2_PAY_1' and "promotions"."percentage" is null)
      )),
	CONSTRAINT "promotions_validity_check" CHECK ("promotions"."ends_at" is null or "promotions"."ends_at" > "promotions"."starts_at")
);
--> statement-breakpoint
ALTER TABLE "online_order_items" ADD COLUMN "discount_amount" numeric(12, 2) DEFAULT '0' NOT NULL;--> statement-breakpoint
ALTER TABLE "online_order_items" ADD COLUMN "promotion_id" integer;--> statement-breakpoint
ALTER TABLE "online_order_items" ADD COLUMN "promotion_type_snapshot" varchar(40);--> statement-breakpoint
ALTER TABLE "online_order_items" ADD COLUMN "promotion_name_snapshot" varchar(160);--> statement-breakpoint
ALTER TABLE "online_order_items" ADD COLUMN "promotion_value_snapshot" integer;--> statement-breakpoint
ALTER TABLE "promotion_categories" ADD CONSTRAINT "promotion_categories_promotion_id_promotions_id_fk" FOREIGN KEY ("promotion_id") REFERENCES "public"."promotions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "promotion_categories" ADD CONSTRAINT "promotion_categories_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "promotion_products" ADD CONSTRAINT "promotion_products_promotion_id_promotions_id_fk" FOREIGN KEY ("promotion_id") REFERENCES "public"."promotions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "promotion_products" ADD CONSTRAINT "promotion_products_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "promotions" ADD CONSTRAINT "promotions_created_by_user_id_users_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "promotions" ADD CONSTRAINT "promotions_updated_by_user_id_users_id_fk" FOREIGN KEY ("updated_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "promotion_categories_category_id_idx" ON "promotion_categories" USING btree ("category_id");--> statement-breakpoint
CREATE INDEX "promotion_products_product_id_idx" ON "promotion_products" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "promotions_active_validity_idx" ON "promotions" USING btree ("is_active","starts_at","ends_at");--> statement-breakpoint
ALTER TABLE "online_order_items" ADD CONSTRAINT "online_order_items_promotion_id_promotions_id_fk" FOREIGN KEY ("promotion_id") REFERENCES "public"."promotions"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "online_order_items_promotion_id_idx" ON "online_order_items" USING btree ("promotion_id");--> statement-breakpoint
ALTER TABLE "online_order_items" ADD CONSTRAINT "online_order_items_discount_non_negative" CHECK ("online_order_items"."discount_amount" >= 0);--> statement-breakpoint
ALTER TABLE "online_order_items" ADD CONSTRAINT "online_order_items_amounts_consistent" CHECK ("online_order_items"."subtotal" + "online_order_items"."discount_amount" = "online_order_items"."unit_price" * "online_order_items"."quantity");--> statement-breakpoint
ALTER TABLE "online_order_items" ADD CONSTRAINT "online_order_items_promotion_snapshot_check" CHECK ((
        ("online_order_items"."promotion_id" is null
          and "online_order_items"."promotion_type_snapshot" is null
          and "online_order_items"."promotion_name_snapshot" is null
          and "online_order_items"."promotion_value_snapshot" is null
          and "online_order_items"."discount_amount" = 0)
        or
        ("online_order_items"."promotion_id" is not null
          and "online_order_items"."promotion_type_snapshot" in ('PERCENTAGE_DISCOUNT', 'BUY_2_PAY_1')
          and "online_order_items"."promotion_name_snapshot" is not null
          and (
            ("online_order_items"."promotion_type_snapshot" = 'PERCENTAGE_DISCOUNT' and "online_order_items"."promotion_value_snapshot" between 1 and 99)
            or ("online_order_items"."promotion_type_snapshot" = 'BUY_2_PAY_1' and "online_order_items"."promotion_value_snapshot" is null)
          ))
      ));